table dimdata
	lineageTag: 3ae2da11-9fa9-4726-b383-50b86fb6d995

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24975a51-8bd6-486e-b2e1-7f29f8499827
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 929f8e56-61b8-4598-a7cc-051ced69bdd0
			defaultHierarchy: LocalDateTable_f6a58413-03a4-4e4b-86f4-9ad52ef620c4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Number'
		dataType: int64
		formatString: 0
		lineageTag: 838eee11-0424-46ff-9fc4-f02ed3161f6a
		summarizeBy: sum
		sourceColumn: Day Number

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 4f11780f-71dc-414b-9ea3-95fc319e4b4a
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: e4e39fd3-4b40-472a-a277-81a14ddef67e
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Short Month'
		dataType: string
		lineageTag: 98f74879-9619-48c6-a557-7c471ad3fc14
		summarizeBy: none
		sourceColumn: Short Month

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 1763de74-40ea-4c6c-9f53-fd9fc68d457a
		summarizeBy: sum
		sourceColumn: Calendar Month Number

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Label'
		dataType: string
		lineageTag: 2805a878-f72f-4c23-a1fa-3a62a4b1cc02
		summarizeBy: none
		sourceColumn: Calendar Month Label

		annotation SummarizationSetBy = Automatic

	column 'Calendar Year'
		dataType: int64
		formatString: 0
		lineageTag: 06a16a43-d262-415c-8e4c-5c99461c54a7
		summarizeBy: sum
		sourceColumn: Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Calendar Year Label'
		dataType: string
		lineageTag: 53e78fb1-e8c4-4571-98f2-31c0f022b1e5
		summarizeBy: none
		sourceColumn: Calendar Year Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 4581a629-5ac6-4859-80ca-a4e44fa02d99
		summarizeBy: sum
		sourceColumn: Fiscal Month Number

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Label'
		dataType: string
		lineageTag: 4919dd1f-af16-4cad-84c8-355d03991242
		summarizeBy: none
		sourceColumn: Fiscal Month Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: bdb9274f-1123-4ed3-a8ec-95499089d5d5
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Label'
		dataType: string
		lineageTag: 5ed608a9-fdcf-407b-8727-185baf2690d9
		summarizeBy: none
		sourceColumn: Fiscal Year Label

		annotation SummarizationSetBy = Automatic

	column 'ISO Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 8b4c97cb-2832-479e-9af9-d8bf80d8cbfa
		summarizeBy: sum
		sourceColumn: ISO Week Number

		annotation SummarizationSetBy = Automatic

	partition dimdata = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\ahmed\Downloads\WWI(data set)"),
				    #"C:\Users\ahmed\Downloads\WWI(data set)\_DimDate csv" = Source{[#"Folder Path"="C:\Users\ahmed\Downloads\WWI(data set)\",Name="DimDate.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\ahmed\Downloads\WWI(data set)\_DimDate csv",[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Day Number", Int64.Type}, {"Day", Int64.Type}, {"Month", type text}, {"Short Month", type text}, {"Calendar Month Number", Int64.Type}, {"Calendar Month Label", type text}, {"Calendar Year", Int64.Type}, {"Calendar Year Label", type text}, {"Fiscal Month Number", Int64.Type}, {"Fiscal Month Label", type text}, {"Fiscal Year", Int64.Type}, {"Fiscal Year Label", type text}, {"ISO Week Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

