table dimstockitem
	lineageTag: e7def56b-c67f-4d01-a0c6-9a290f4a2e8a

	column 'Stock Item Key'
		dataType: int64
		formatString: 0
		lineageTag: 76b8175a-fd4c-4f93-b3c9-6e6f4ddef5ca
		summarizeBy: none
		sourceColumn: Stock Item Key

		annotation SummarizationSetBy = Automatic

	column 'WWI Stock Item ID'
		dataType: int64
		formatString: 0
		lineageTag: 11909b10-ea70-427b-b45f-8191f68bc97f
		summarizeBy: none
		sourceColumn: WWI Stock Item ID

		annotation SummarizationSetBy = Automatic

	column 'Stock Item'
		dataType: string
		lineageTag: db738b20-aa46-48fe-9039-7f5de5140527
		summarizeBy: none
		sourceColumn: Stock Item

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 90d9baf3-981d-4fe9-a3b8-b561fb053c0f
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Selling Package'
		dataType: string
		lineageTag: 890ada07-c2b3-4420-a647-5fbf92b12f9f
		summarizeBy: none
		sourceColumn: Selling Package

		annotation SummarizationSetBy = Automatic

	column 'Buying Package'
		dataType: string
		lineageTag: 879cef03-d9b6-4187-865a-75685914bdab
		summarizeBy: none
		sourceColumn: Buying Package

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 1fff24ec-9adb-429c-b28e-39c5ef7cc333
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 9d48d028-a012-436c-b6dc-a94f9127afaa
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column 'Lead Time Days'
		dataType: int64
		formatString: 0
		lineageTag: d4983414-bcd5-4cd2-ae9d-43197f5ef5e9
		summarizeBy: none
		sourceColumn: Lead Time Days

		annotation SummarizationSetBy = Automatic

	column 'Quantity Per Outer'
		dataType: int64
		formatString: 0
		lineageTag: 64632fe9-3742-4dee-b79f-ee498985b85e
		summarizeBy: none
		sourceColumn: Quantity Per Outer

		annotation SummarizationSetBy = Automatic

	column 'Is Chiller Stock'
		dataType: int64
		formatString: 0
		lineageTag: 835e396c-ce69-4d73-91c4-e611b827da72
		summarizeBy: none
		sourceColumn: Is Chiller Stock

		annotation SummarizationSetBy = Automatic

	column Barcode
		dataType: string
		lineageTag: b8e25b5c-109c-454e-8dc5-02ce60617fe6
		summarizeBy: none
		sourceColumn: Barcode

		annotation SummarizationSetBy = Automatic

	column 'Tax Rate'
		dataType: int64
		formatString: 0
		lineageTag: 5e4f661b-6b67-489e-b564-c4478e3a8ac8
		summarizeBy: none
		sourceColumn: Tax Rate

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: f55f379b-6168-4549-8e1d-3d5431ab61b5
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Recommended Retail Price'
		dataType: string
		lineageTag: 0805defe-527d-4622-b950-06e5384f155a
		summarizeBy: none
		sourceColumn: Recommended Retail Price

		annotation SummarizationSetBy = Automatic

	column 'Typical Weight Per Unit'
		dataType: double
		lineageTag: a7677519-01c7-445b-9f21-92151bf0c3c7
		summarizeBy: none
		sourceColumn: Typical Weight Per Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Photo
		dataType: string
		lineageTag: 19727b72-9eae-4d7b-976e-ae013a6b0c65
		summarizeBy: none
		sourceColumn: Photo

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: string
		lineageTag: 70081478-6ab5-468a-9525-401779a02dce
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Valid From'
		dataType: string
		lineageTag: 0008bdc8-0350-46e8-9eea-812d271045fa
		summarizeBy: none
		sourceColumn: Valid From

		annotation SummarizationSetBy = Automatic

	column 'Valid To'
		dataType: string
		lineageTag: 131490e3-4221-4741-99e4-53424e37fcaa
		summarizeBy: none
		sourceColumn: Valid To

		annotation SummarizationSetBy = Automatic

	column 'Lineage Key'
		dataType: int64
		formatString: 0
		lineageTag: 531de2a6-2f6c-4cb7-a203-5f96abff4eb7
		summarizeBy: none
		sourceColumn: Lineage Key

		annotation SummarizationSetBy = Automatic

	partition dimstockitem = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\ahmed\Downloads\WWI(data set)"),
				    #"C:\Users\ahmed\Downloads\WWI(data set)\_DimStockItem csv" = Source{[#"Folder Path"="C:\Users\ahmed\Downloads\WWI(data set)\",Name="DimStockItem.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\ahmed\Downloads\WWI(data set)\_DimStockItem csv",[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Stock Item Key", Int64.Type}, {"WWI Stock Item ID", Int64.Type}, {"Stock Item", type text}, {"Color", type text}, {"Selling Package", type text}, {"Buying Package", type text}, {"Brand", type text}, {"Size", type text}, {"Lead Time Days", Int64.Type}, {"Quantity Per Outer", Int64.Type}, {"Is Chiller Stock", Int64.Type}, {"Barcode", type text}, {"Tax Rate", Int64.Type}, {"Unit Price", type number}, {"Recommended Retail Price", type text}, {"Typical Weight Per Unit", type number}, {"Photo", type text}, {"Discount", type text}, {"Valid From", type text}, {"Valid To", type text}, {"Lineage Key", Int64.Type}}),
				    #"Removed Top Rows1" = Table.Skip(#"Changed Type1",1)
				in
				    #"Removed Top Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

